version: '3'
services:
  node:
    container_name: user
    restart: always
    build: .
    ports:
      - 3001:3001
    networks:
      - scale-commerce-network
    volumes:
      - ./:/code
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    networks:
      - scale-commerce-network
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:


networks:
  scale-commerce-network:
    external:
      name: scale-commerce-network
