version: '3'
services:
  node:
    container_name: user
    restart: always
    build: .
    ports:
      - 3001:3001
    volumes:
      - ./:/code
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
